//
// Generated file, do not edit! Created by opp_msgc 4.3 from id.msg.
//

#ifndef _ID_M_H_
#define _ID_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif


namespace BranchComp {

/**
 * Class generated from <tt>id.msg</tt> by opp_msgc.
 * <pre>
 * class Id {
 * 	long value;
 * }
 * </pre>
 */
class Id : public ::cObject
{
  protected:
    long value_var;

  private:
    void copy(const Id& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Id&);

  public:
    Id();
    Id(const Id& other);
    virtual ~Id();
    Id& operator=(const Id& other);
    virtual Id *dup() const {return new Id(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual long getValue() const;
    virtual void setValue(long value);
};

inline void doPacking(cCommBuffer *b, Id& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Id& obj) {obj.parsimUnpack(b);}

}; // end namespace BranchComp

#endif // _ID_M_H_
